name: SpanishFlashcards
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: '17.0'
targets:
  SpanishFlashcards:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources
    info:
      path: Resources/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities: [arm64]
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        NSMicrophoneUsageDescription: This app requires access to the microphone to record audio for flashcards.
